# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender')], max_length=1)),
                ('age', models.IntegerField()),
                ('timing', models.CharField(choices=[('Morn', '10 AM - 1 PM'), ('Aft', '2 PM - 5 PM'), ('Eve', '6 PM - 9 PM')], max_length=4)),
                ('specialist', models.CharField(choices=[('Cardiologist', 'car'), ('Plastic Surgeon', 'pla'), ('Psychiatrist', 'psy'), ('Radiologist', 'rad'), ('Surgeon', 'sur')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('bloodgroup', models.CharField(blank=True, choices=[('apos', 'A+'), ('aneg', 'A-'), ('bpos', 'B+'), ('bneg', 'B-'), ('opos', 'O+'), ('oneg', 'O-'), ('abpos', 'AB+'), ('abneg', 'AB-')], max_length=5)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender')], max_length=1)),
                ('age', models.IntegerField()),
                ('address', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
