# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(choices=[('Cardiologist', 'car'), ('Plastic Surgeon', 'pla'), ('Psychiatrist', 'psy'), ('Radiologist', 'rad'), ('Surgeon', 'sur')], max_length=20),
        ),
    ]
