# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190308_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(choices=[('car', 'Cardiologist'), ('pl', 'Plastic Surgeon'), ('psy', 'Psychiatrist'), ('rad', 'Radiologist'), ('sur', 'Surgeon')], max_length=20),
        ),
    ]
