# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190308_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('apos', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donate',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=15),
        ),
    ]
